_id: $App~~baking-bread
defaultLook: materia
defaultPrimaryColor: eb6864
defaultSecondaryColor: aaaaaa
defaultTheme: Clean
category: Food & Travel
description: 'Presentation, Online Orders, Contact'
pages:
    - _footer.html
    - _form.html
    - _head.html
    - _nav.html
    - _scripts.html
    - index.html
name: baking-bread
