_id: $App~~baking-bread
defaultLook: basic
defaultPrimaryColor: 008cba
defaultSecondaryColor: eeeeee
defaultTheme: Clean
category: Food & Travel
description: 'Presentation, Online Orders, Contact'
pages:
    - _footer.html
    - _form.html
    - _head.html
    - _nav.html
    - _scripts.html
    - index.html
