image: node:8.9.4

before_script:
- chmod +x ci/install-chrome
- ci/install-chrome
- rm -rf node_modules
- npm install
- cd server && rm -rf node_modules && npm install
- cd ..

test:
  script:
  # Run npm test in virtual display mode
  - npm test
  - cd server && npm test
  - cd ..
  - npm run e2e
  cache:
    untracked: true
  retry: 2
