image: node:latest

before_script:
- chmod +x ci/install-chrome
- ci/install-chrome
- npm install

test:
  script:
  # Run npm test in virtual display mode
  - npm test
  - npm run e2e
  - cd server && npm test
  cache:
    untracked: true
