variables:
  GIT_DEPTH: 5

stages:
  - build
  - test_and_bundle
  - build_images_and_deploy_dev
  - e2e_dev_env
  - build_images_and_deploy_staging
  - e2e_staging
  - build_images_and_deploy_production
  - e2e_production
  - cleanup


.only_for_staging_and_production: &only_for_staging_and_production
  only:
    - master
    - tags

.only_for_production: &only_for_production
  only:
    - tags

build:
  stage: build
  script:
    - npm install
    - npm run compile
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - node_modules/
      - tsc-out/

bundle:
  stage: test_and_bundle
  script:
    - npm run bundle
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - node_modules/
      - tsc-out/
      - dist-be/
      - formuladb/

build_images_and_deploy_dev:
  stage: build_images_and_deploy_dev
  script:
    - ls dist-be tsc-out 
    - export KUBECONFIG="${PWD}/k8s/production-kube-config.conf"
    - ./ci/jobs.sh $CI_JOB_NAME
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - node_modules/
      - tsc-out/
      - dist-be/
      - formuladb/
      - formuladb-e2e/

test_mem:
  stage: test_and_bundle
  script:
    - npm test
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - node_modules/
      - tsc-out/
    policy: pull

test_fe:
  stage: test_and_bundle
  script:
    - npm run test:fe
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - node_modules/
      - tsc-out/
    policy: pull

test_postgres:
  stage: build_images_and_deploy_dev
  script:
    - ./ci/jobs.sh $CI_JOB_NAME
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - node_modules/
      - tsc-out/
    policy: pull

test_stress:
  stage: test_and_bundle
  retry: 2
  script:
    - ./ci/jobs.sh $CI_JOB_NAME
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - node_modules/
      - tsc-out/
    policy: pull

test_api:
  stage: e2e_dev_env
  script:
    - bash api-tests.sh
  artifacts:
    reports:
      junit: api-tests.junit.xml
    when: always    

e2e_dev_env:
  stage: e2e_dev_env
  retry: 2
  script:
    - export KUBECONFIG="${PWD}/k8s/production-kube-config.conf"
    - ./ci/jobs.sh $CI_JOB_NAME
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - node_modules/
      - tsc-out/
      - dist-be/
      - formuladb/
      - formuladb-e2e/

build_images_and_deploy_staging:
  stage: build_images_and_deploy_staging
  script:
    - export KUBECONFIG="${PWD}/k8s/production-kube-config.conf"
    - ./ci/jobs.sh $CI_JOB_NAME
  environment:
    name: staging
    url: https://staging.formuladb.io
  <<: *only_for_staging_and_production
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - node_modules/
      - tsc-out/
      - dist-be/
      - formuladb/
      - formuladb-e2e/
    policy: pull

e2e_staging:
  stage: e2e_staging
  script:
    - export KUBECONFIG="${PWD}/k8s/production-kube-config.conf"
    - ./ci/jobs.sh $CI_JOB_NAME
  <<: *only_for_staging_and_production
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - node_modules/
      - tsc-out/
      - dist-be/
      - formuladb/
      - formuladb-e2e/
    policy: pull

build_images_and_deploy_production:
  stage: build_images_and_deploy_production
  script:
    - export KUBECONFIG="${PWD}/k8s/production-kube-config.conf"
    - ./ci/jobs.sh $CI_JOB_NAME
  environment:
    name: production
    url: https://formuladb.io
  <<: *only_for_production
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - node_modules/
      - tsc-out/
      - dist-be/
      - formuladb/
      - formuladb-e2e/
    policy: pull

e2e_production:
  stage: e2e_production
  script:
    - export KUBECONFIG="${PWD}/k8s/production-kube-config.conf"
    - ./ci/jobs.sh $CI_JOB_NAME
  <<: *only_for_production
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - node_modules/
      - tsc-out/
      - dist-be/
      - formuladb/
      - formuladb-e2e/
    policy: pull

cleanup:
  stage: cleanup
  script:
    - export KUBECONFIG="${PWD}/k8s/production-kube-config.conf"
    - ./ci/jobs.sh $CI_JOB_NAME
  when: always
