stages:
  - build_and_test
  - cleanup_build

build:
  stage: build_and_test
  script:
    - cd storage && npm install 
    - cd ..
    - cd core && npm install 
    - cd ..
    - cd be && npm install
    - cd ..
    - cd fe && npm install
    - cd ..
    - cd be
    - npm run compile
    - docker build -t formuladb-be .
    - echo "TODO push to registry"
    - docker tag formuladb-be registry.gitlab.com/metawiz/febe/formuladb-be:0.0.1
    - docker push registry.gitlab.com/metawiz/febe/formuladb-be:0.0.1
    - cd ..
    - cd fe
    - npm run build -- --prod --deploy-url=/formuladb/ --base-href=/formuladb/ --source-map
    - docker build -t formuladb-fe .
    - docker tag formuladb-fe registry.gitlab.com/metawiz/febe/formuladb-fe:0.0.1
    - docker push registry.gitlab.com/metawiz/febe/formuladb-fe:0.0.1
    - cd ..

test:
  stage: build_and_test
  script:
    - docker-compose down
    - FRMDB_RELEASE=0.0.1 docker-compose up -d
    - cd be
    - npm test
    - FRMDB_STORAGE=postgres npm test
    - cd ..
    - docker-compose down
    - docker image prune --all -f

    # - cd fe && npm test -- --watch=false
    # - cd ..
  # artifacts:
  #   paths:
  #     - coverage/
  #     - karma.log
  retry: 2


cleanup_build_job:
  stage: cleanup_build
  script:
    - docker-compose down
    - docker image prune --all -f
  when: on_failure
