# image: node:8.9.4

# before_script:
  # - chmod +x ci/install-chrome
  # - ci/install-chrome

test:
  stage: test
  script:
    - cd storage && npm install && npm run compile && npm run initpgdb
    - cd ..
    - cd be && npm install
    - cd ..
    - cd fe && npm install
    - cd ..
    - cd be && npm test
    - cd ..
    # - cd fe && npm test -- --watch=false
    # - cd ..
  # artifacts:
  #   paths:
  #     - coverage/
  #     - karma.log
  retry: 2

# pages:
#   stage: deploy
#   script:
#     - mv coverage/ public/
#   dependencies:
#     - test
#   artifacts:
#     paths:
#       - public
#     expire_in: 30 days
#   only:
#     - master
