# image: node:8.9.4

# before_script:
  # - chmod +x ci/install-chrome
  # - ci/install-chrome
# TODO 
# TODO THIS should be done only on release branches and get the image version from the name of the branch
# TODO 
build:
  stage: build
  script:
    - cd storage && npm install 
    - cd ..
    - cd core && npm install 
    - cd ..
    - cd be && npm install
    - cd ..
    - cd fe && npm install
    - cd ..
    - cd be
    - npm run compile
    - docker build -t formuladb-be .
    - echo "TODO push to registry"
    - docker tag formuladb-be registry.gitlab.com/metawiz/febe/formuladb-be:0.0.1
    - docker push registry.gitlab.com/metawiz/febe/formuladb-be:0.0.1
    - cd ..
    - cd fe
    - npm run build -- --prod --deploy-url=/formuladb/ --base-href=/formuladb/ --source-map
    - docker build -t formuladb-fe .
    - docker tag formuladb-fe registry.gitlab.com/metawiz/febe/formuladb-fe:0.0.1
    - docker push registry.gitlab.com/metawiz/febe/formuladb-fe:0.0.1
    - cd ..

test:
  stage: test
  script:
    - docker-compose down
    - FRMDB_RELEASE=0.0.1 docker-compose up -d
    - cd be
    - npm test
    - FRMDB_STORAGE=postgres npm test
    - cd ..
    - docker-compose down
    - docker image prune --all -f

    # - cd fe && npm test -- --watch=false
    # - cd ..
  # artifacts:
  #   paths:
  #     - coverage/
  #     - karma.log
  retry: 2


# pages:
#   stage: deploy
#   script:
#     - mv coverage/ public/
#   dependencies:
#     - test
#   artifacts:
#     paths:
#       - public
#     expire_in: 30 days
#   only:
#     - master
