image: node:latest

before_script:
- chmod +x ci/install-chrome
- ci/install-chrome
- npm install
- cd server && npm install
- cd ..
- which ng
- which tsc
- ng --version

test:
  script:
  # Run npm test in virtual display mode
  - npm test
  - cd server && npm test
  - cd ..
  - npm run e2e
  cache:
    untracked: true
  retry: 2
