test:
  stage: test
  script:
    - docker run
      --rm
      --name ci-with-video
      --cap-add=SYS_ADMIN
      --user centos
      registry.gitlab.com/metawiz/febe/ci-with-video:1.0.0
      bash -c "
        source ~/.bashrc
          && cd
          && git clone https://gitlab-ci-token:$CI_BUILD_TOKEN@gitlab.com/metawiz/febe.git
          && cd febe/
          && git checkout $CI_COMMIT_REF_NAME
          && cd storage
          && npm install
          && cd ..
          && cd core
          && npm install
          && cd ..
          && cd be
          && npm install
          && cd ..
          && cd fe/
          && npm install
          && npm run build
          && ng e2e
        "
