version: "3.0"

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pg-persistence:/var/lib/postgresql/data
  febe:
    image: registry.gitlab.com/metawiz/febe/formuladb-febe:${FRMDB_RELEASE:-unknown_FRMDB_RELEASE}
    depends_on:
      - db
    environment:
      FRMDB_STORAGE: "postgres"
      PGHOST: "db"
    ports:
      - "8084:3000"
      # publish node inspector port. By default the V8 inspector listens on 127.0.0.1 only.
      # To debug, run `socat -d tcp-listen:9229,reuseaddr,fork,bind=`hostname -i` tcp:127.0.0.1:9229 &` from inside the BE container
      # source maps not working in chrome for node ? https://github.com/webpack/webpack/issues/2612
      - "9229:9229"
  maps:
    image: registry.gitlab.com/metawiz/febe/formuladb-maps:${FRMDB_RELEASE:-unknown_FRMDB_RELEASE}
    command: nginx-debug -g 'daemon off;'
    ports:
      - "8085:80"
  minio:
    image: registry.gitlab.com/metawiz/febe/formuladb-minio:${FRMDB_RELEASE:-unknown_FRMDB_RELEASE}
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: minio server /data/minio/
    volumes:
      - object-storage:/data
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm local;
      /usr/bin/mc config host add local http://minio:9000 minio minio123;
      /usr/bin/mc policy public local/assets;
      exit 0;
      "

volumes:
  pg-persistence:
  object-storage:
