version: "3.0"

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pg-persistence:/var/lib/postgresql/data
  be:
    image: registry.gitlab.com/metawiz/febe/formuladb-be:${FRMDB_RELEASE:-unknown_FRMDB_RELEASE}
    environment:
      FRMDB_STORAGE: "postgres"
    ports:
      # publish node inspector port. By default the V8 inspector listens on 127.0.0.1 only.
      # To debug, run `socat -d tcp-listen:9229,reuseaddr,fork,bind=`hostname -i` tcp:127.0.0.1:9229 &` from inside the BE container
      # source maps not working in chrome for node ? https://github.com/webpack/webpack/issues/2612
      - "9229:9229"
  fe:
    image: registry.gitlab.com/metawiz/febe/formuladb-fe:${FRMDB_RELEASE:-unknown_FRMDB_RELEASE}
    ports:
      - "8084:8084"
    volumes:
      - $PWD/auth.htpasswd:/etc/nginx/auth.htpasswd
  minio:
    image: minio/minio:RELEASE.2019-03-06T22-47-10Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: minio server /data/
    volumes:
      - object-storage:/data

volumes:
  pg-persistence:
  object-storage:
