version: "3.0"

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pg-persistence:/var/lib/postgresql/data
  be:
    image: registry.gitlab.com/metawiz/febe/formuladb-be:${FRMDB_RELEASE:-unknown_FRMDB_RELEASE}
    environment:
      FRMDB_STORAGE: "postgres"
    ports:
      # publish node inspector port. By default the V8 inspector listens on 127.0.0.1 only.
      # To debug, run `socat -d tcp-listen:9229,reuseaddr,fork,bind=`hostname -i` tcp:127.0.0.1:9229 &` from inside the BE container
      - "9229:9229"
  fe:
    image: registry.gitlab.com/metawiz/febe/formuladb-fe:${FRMDB_RELEASE:-unknown_FRMDB_RELEASE}
    ports:
      - "8084:8084"
    volumes:
      - $PWD/auth.htpasswd:/etc/nginx/auth.htpasswd

volumes:
  pg-persistence:
