openapi: 3.0.0
info:
  title: FormulaDB Client API
  description: read/write records, transactions
  version: 0.0.23
servers:
  - url: /formuladb/api/v0.0.23
    description: formuladb base path
paths:
  /{app}/{table}/putRecord:
    post:
      summary: Save record and update all records with formulas that depend on the saved record.
      description: Save record and update all records with formulas that depend on the saved record.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServerEvent'
        required: true
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
components:
  schemas:
