apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/metawiz/febe/formuladb-be
    context: .
    sync:
      manual:
      - src: dist-be/**/*.js*
        dest: /
      - src: formuladb/**/*
        dest: /wwwroot/formuladb
        strip: formuladb
      - src: formuladb-env/**/*
        dest: /wwwroot/git/formuladb-env
        strip: formuladb-env
      - src: skaffold.yaml
        dest: /
      - src: k8s/**/*
        dest: /
      - src: scripts/*
        dest: /scripts
        strip: scripts
    docker:
      dockerfile: Dockerfile.be
deploy:
  kustomize:
    paths:
    - k8s/overlays/production
profiles:
- name: dev
  patches:
  - op: add
    path: /build/artifacts/0/docker/buildArgs
    value:
      BUILD_DEVELOPMENT: 1
  - op: replace
    path: /deploy/kustomize/paths/0
    value: k8s/overlays/development
- name: ci
  patches:
  - op: replace
    path: /deploy/kustomize/paths/0
    value: k8s/overlays/ci
- name: staging
  patches:
  - op: replace
    path: /deploy/kustomize/paths/0
    value: k8s/overlays/staging
- name: production
  patches:
  - op: replace
    path: /deploy/kustomize/paths/0
    value: k8s/overlays/production
- name: client
  patches:
  - op: replace
    path: /deploy/kustomize/paths/0
    value: k8s/overlays/client
