apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/metawiz/febe/formuladb-be
    context: .
    sync:
      manual:
      # Sync all the javascript files that are in the dist-be folder
      # with the container's root
      - src: 'dist-be/**/*.js*'
        dest: .
    docker:
      dockerfile: Dockerfile.be
      buildArgs: {}
deploy:
  kustomize:
    path: k8s/overlays/production
profiles:
  - name: dev
    patches:
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value:
          BUILD_DEVELOPMENT: 1
      - op: replace
        path: /deploy/kustomize/path
        value: k8s/overlays/development
  - name: staging
    patches:
      - op: replace
        path: /deploy/kustomize/path
        value: k8s/overlays/staging
  - name: production
    patches:
      - op: replace
        path: /deploy/kustomize/path
        value: k8s/overlays/production
  - name: biz
    patches:
      - op: replace
        path: /deploy/kustomize/path
        value: k8s/overlays/biz
