apiVersion: skaffold/v2alpha3
kind: Config
build:
  cluster:
    randomPullSecret: true
    randomDockerConfigSecret: true
    pullSecretName: regcred
    dockerConfig:
      path: ci/docker-config.json
  artifacts:
  - image: registry.formuladb.io/formuladb/febe/formuladb-be
    context: .
    sync:
      manual:
      - src: dist-be/**/*.js*
        dest: /
      - src: formuladb/**/*
        dest: /wwwroot/formuladb
        strip: formuladb
      - src: git/formuladb-env/**/*
        dest: /formuladb-env
        strip: git/formuladb-env
      - src: skaffold.yaml
        dest: /
      - src: k8s/**/*
        dest: /
      - src: scripts/*
        dest: /scripts
        strip: scripts
    kaniko:
      dockerfile: Dockerfile.be
      cache: {}
  # - image: registry.formuladb.io/formuladb/febe/code-server
  #   context: .
  #   kaniko:
  #     dockerfile: Dockerfile.code
  #     cache: {}
deploy:
  kustomize:
    paths:
    - k8s/overlays/production
profiles:
- name: localdev
  patches:
  - op: remove
    path: /build/cluster
  - op: remove
    path: /build/artifacts/0/kaniko
  # - op: remove
  #   path: /build/artifacts/1/kaniko
  - op: add
    path: /build/artifacts/0/docker
    value:
      dockerfile: Dockerfile.be
      buildArgs:
        BUILD_DEVELOPMENT: 1
  # - op: add
  #   path: /build/artifacts/1/docker
  #   value:
  #     dockerfile: Dockerfile.code
  #     buildArgs:
  - op: replace
    path: /deploy/kustomize/paths/0
    value: k8s/overlays/localdev
- name: ci
  patches:
  - op: add
    path: /build/artifacts/0/kaniko/buildArgs
    value:
      BUILD_CI: 1
  - op: replace
    path: /deploy/kustomize/paths/0
    value: k8s/overlays/ci
- name: staging
  patches:
  - op: replace
    path: /deploy/kustomize/paths/0
    value: k8s/overlays/staging    
- name: client
  patches:
  - op: replace
    path: /deploy/kustomize/paths/0
    value: k8s/overlays/client
- name: production
  patches:
  - op: replace
    path: /deploy/kustomize/paths/0
    value: k8s/overlays/production
- name: k3s
  patches:
  - op: remove
    path: /build/cluster
  - op: remove
    path: /build/artifacts/0/kaniko
  - op: add
    path: /build/artifacts/0/docker
    value:
      dockerfile: Dockerfile.be
      buildArgs:
        BUILD_DEVELOPMENT: 1    
  - op: replace
    path: /deploy/kustomize/paths/0
    value: k8s/overlays/k3s
    # value: k8s/be
