_id: $App~~hotel-booking
defaultLook: basic
defaultPrimaryColor: ffc208
defaultSecondaryColor: 353b41
defaultTheme: Clean
category: 'Food & Travel, Booking & Appointments'
description: 'Room Booking, Galery, Contact, Blog'
pages:
    - _footer.html
    - _form.html
    - _head.html
    - _nav.html
    - _scripts.html
    - about.html
    - booking.html
    - contact.html
    - gallery.html
    - index.html
