elasticsearchHosts: http://formuladb-master:9200
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: es-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    certmanager.k8s.io/issuer: "kibana-prod"
    nginx.ingress.kubernetes.io/app-root: /analytics
  hosts:
    - kibana.formuladb.io
  tls:
    - secretName: certificate-kibana-prod
      hosts:
        - kibana.formuladb.io
kibanaConfig:
  kibana.yml: |
    server:
      basePath: "/analytics"
      rewriteBasePath: true
healthCheckPath: "/analytics/app/kibana"
