stages:
  - publish

publish:
  stage: publish
  script:
    - FILES=`git ls-files | grep -v .gitlab-ci.yml`
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/frmdb-apps/ci-tools.git
    - cd ci-tools
    - npm install
    - source tools.sh
    - cd ..
    - NODE_PATH=ci-tools/node_modules PATH_PREFIX=frmdb-themes/$CI_PROJECT_NAME/ upload-assets $FILES
  only:
    refs:
      - master
