apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Release.Name }}
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: be
  name: be
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: be
    spec:
      imagePullSecrets:
      - name: gitlab-febe-docker-registry
      containers:
      - env:
        - name: FRMDB_STORAGE
          value: postgres
        image: registry.gitlab.com/metawiz/febe/formuladb-be:0.0.4
        name: be
        ports:
        - containerPort: 9229
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}

