apiVersion: batch/v1
kind: Job
metadata:
  name: createbuckets
  namespace: {{ .Release.Name }}
spec:
  template:
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - ' /usr/bin/mc config host rm local; /usr/bin/mc config host add local http://minio:9000
          minio minio123; /usr/bin/mc policy public local/assets; exit 0; '
        image: minio/mc
        name: createbuckets
        resources: {}
      restartPolicy: Never
  backoffLimit: 4

