apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: {{ .Release.Name }}
  name: formuladb
spec:
  hosts:
  - {{ .Release.Name }}.formuladb.online
  gateways:
  - formuladb-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: fe
        port:
          number: 8084


