_id: $App~~law-firm
defaultLook: basic
defaultPrimaryColor: 008cba
defaultSecondaryColor: eeeeee
defaultTheme: Clean
category: Consulting
description: 'Contracts/documents, portfolio, testimonials, appointments'
pages:
    - _footer.html
    - _form.html
    - _head.html
    - _nav.html
    - _scripts.html
    - index.html
name: law-firm
