_id: FRMDB_SCHEMA~~formuladb-internal--formuladb.io
entityIds:
    - SampleApp
    - WishListRequest
    - AppCategory
    - ContactRequest
    - $User
    - $Dictionary
    - $Currency
    - App_Template
