apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
        listen         80;
        server_name  formuladb.online www.formuladb.online formuladb.io www.formuladb.io;
        root         /usr/share/nginx/html;
        rewrite  ^/$  /index.html  last;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location /formuladb-api {
            proxy_pass http://be:8084/formuladb-api;
        }

        location @root_fallback {
            proxy_pass http://be:8084;
        }

        # case-insensitive matching
        location ~* /formuladb-editor/(.*)$ {
            proxy_pass https://storage.googleapis.com/formuladb-static-assets/vvvebjs/$1;
        }

        location ~* /formuladb/(.*)$ {
            proxy_pass https://storage.googleapis.com/formuladb-static-assets/fe/$1;
        }

        location ~* (/assets/.+(?<!\.html))$ {
            proxy_pass https://storage.googleapis.com/formuladb-static-assets/portal/public/$1;
            error_page 404 = @root_fallback;
            proxy_intercept_errors on;
        }

        location ~* (/.+(?<!\.html))$ {
            proxy_pass https://storage.googleapis.com/formuladb-static-assets/$1;
            error_page 404 = @root_fallback;
            proxy_intercept_errors on;
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }
