apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: lb
  name: lb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: lb
    spec:
      containers:
      - image: registry.gitlab.com/metawiz/febe/formuladb-lb:0.0.12
        name: lb
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
      restartPolicy: Always
status: {}
