apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: be
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: be
    spec:
      initContainers:
      - name: check-db-ready
        image: postgres:11
        command: ['sh', '-c', 'pg_isready -h db -p 5432 -t 10']
      containers:
      - env:
        - name: DEBUG
          value: express:*
        - name: DEFAULT_USER
        - name: DEV_MODE
        - name: FRMDB_STORAGE
          value: postgres
        - name: PGHOST
          value: db
        - name: GITHOST
          value: git
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/gcp/sa_credentials.json
        - name: FRMDB_AUTH_ENABLED
          value: "true"
        image: registry.gitlab.com/metawiz/febe/formuladb-be
        name: be
        ports:
        - containerPort: 3000
        - containerPort: 9231
        resources: {}
        volumeMounts:
        - name: service-account-credentials
          mountPath: /etc/gcp
          readOnly: true
      volumes:
      - name: service-account-credentials
        secret:
          secretName: service-account-credentials
          items:
          - key: sa_json
            path: sa_credentials.json
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
status: {}
