apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: db
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: postgres
        image: postgres:11
        name: db
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pg-persistence
          subPath: postgres
      restartPolicy: Always
      volumes:
      - name: pg-persistence
        persistentVolumeClaim:
          claimName: pg-persistence
status: {}
