apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: lb
  name: lb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: lb
    spec:
      containers:
      - image: nginx:alpine-perl
        name: lb
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
          name: nginx-conf
        resources: {}
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
status: {}
