apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoibHNvaWNhIiwicGFzc3dvcmQiOiJncmV1ZGVzcGFydDIiLCJlbWFpbCI6ImxhdXJlbnRpdS5zb2ljYUBmb3JtdWxhZGIuaW8iLCJhdXRoIjoiYkhOdmFXTmhPbWR5WlhWa1pYTndZWEowTWc9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: gitlab-febe-docker-registry
type: kubernetes.io/dockerconfigjson
