_id: FRMDB_SCHEMA~~inventory
entities:
  GEN__Currency:
    _id: GEN__Currency
    props:
      code: {name: code, propType_: STRING}
      rate1: {name: rate1, propType_: NUMBER}
      rate2: {name: rate2, propType_: NUMBER}
      rate3: {name: rate3, propType_: NUMBER}
      rate4: {name: rate4, propType_: NUMBER}
      rate5: {name: rate5, propType_: NUMBER}
      _id: {name: _id, propType_: STRING, allowNull: false}
    validations:
      rate1!max: {conditionExpr: {type: BinaryExpression, startIndex: 0, endIndex: 14, origExpr: 'rate1 < 10000 ', operator: <, left: {type: Identifier, startIndex: 0, endIndex: 5, origExpr: rate1, name: rate1}, right: {type: NumberLiteral, startIndex: 8, endIndex: 13, origExpr: '10000', value: 10000, raw: '10000'}}}
    isEditable: true
  GEN__Client:
    _id: GEN__Client
    props:
      code: {name: code, propType_: STRING, allowNull: false}
      username: {name: username, propType_: STRING}
      name: {name: name, propType_: STRING}
      role: {name: role, propType_: STRING}
      password: {name: password, propType_: STRING}
      details: {name: details, propType_: STRING}
      type: {name: type, propType_: STRING}
      parent_code: {name: parent_code, propType_: STRING}
      param1: {name: param1, propType_: STRING}
      state: {name: state, propType_: STRING, allowNull: false}
      _id: {name: _id, propType_: STRING, allowNull: false}
    isEditable: true
  Inventory:
    _id: Inventory
    pureNavGroupingChildren:
      - InventoryProduct
      - InventoryOrder
      - InventoryReceipt
      - InventoryProductUnit
    props:
      _id: {name: _id, propType_: STRING, allowNull: false}
    isEditable: true
  InventoryOrder:
    _id: InventoryOrder
    stateGraph:
      nodes: [PENDING, COMPLETE, APPROVED, PROCESSED, CANCELLED]
      transitions: [{source: PENDING, target: COMPLETE}, {source: COMPLETE, target: APPROVED}, {source: APPROVED, target: PROCESSED}, {source: PENDING, target: CANCELLED}, {source: COMPLETE, target: CANCELLED}, {source: APPROVED, target: CANCELLED}]
    props:
      sales_agent: {name: sales_agent, propType_: STRING, allowNull: false}
      creation_date: {name: creation_date, propType_: DATETIME, allowNull: false}
      order_item_table: {name: order_item_table, propType_: CHILD_TABLE, referencedEntityName: OrderItem, props: {}, isLargeTable: true}
      _id: {name: _id, propType_: STRING, allowNull: false}
    isEditable: true
  OrderItem:
    _id: OrderItem
    props:
      _id: {name: _id, propType_: STRING, allowNull: false}
      product_id: {name: product_id, propType_: REFERENCE_TO, referencedEntityName: ProductLocation, referencedPropertyName: _id}
      quantity: {name: quantity, propType_: NUMBER, allowNull: false}
      error_quantity: {name: error_quantity, propType_: NUMBER}
      client_stock: {name: client_stock, propType_: NUMBER}
      units: {name: units, propType_: CHILD_TABLE, referencedEntityName: InventoryProductUnit}
    autoCorrectionsOnValidationFailed:
      ProductLocation!positiveStock: [{targetPropertyName: quantity, autoCorrectExpr: {type: CallExpression, startIndex: 0, arguments: [{type: NumberLiteral, startIndex: 4, endIndex: 5, origExpr: '0', value: 0, raw: '0'}, {type: BinaryExpression, startIndex: 7, endIndex: 41, origExpr: quantity + $ROW$.available_stock__, operator: +, left: {type: Identifier, startIndex: 7, endIndex: 15, origExpr: quantity, name: quantity}, right: {type: MemberExpression, startIndex: 18, computed: false, object: {type: Identifier, startIndex: 18, endIndex: 23, origExpr: $ROW$, name: $ROW$}, property: {type: Identifier, startIndex: 24, endIndex: 41, origExpr: available_stock__, name: available_stock__}, endIndex: 41, origExpr: $ROW$.available_stock__}}], callee: {type: Identifier, startIndex: 0, endIndex: 3, origExpr: MAX, name: MAX}, endIndex: 42, origExpr: 'MAX(0, quantity + $ROW$.available_stock__)'}}, {targetPropertyName: error_quantity, autoCorrectExpr: {type: CallExpression, startIndex: 0, arguments: [{type: BinaryExpression, startIndex: 4, endIndex: 29, origExpr: $OLD$.quantity - quantity, operator: '-', left: {type: MemberExpression, startIndex: 4, computed: false, object: {type: Identifier, startIndex: 4, endIndex: 9, origExpr: $OLD$, name: $OLD$}, property: {type: Identifier, startIndex: 10, endIndex: 18, origExpr: quantity, name: quantity}, endIndex: 18, origExpr: $OLD$.quantity}, right: {type: Identifier, startIndex: 21, endIndex: 29, origExpr: quantity, name: quantity}}], callee: {type: Identifier, startIndex: 0, endIndex: 3, origExpr: ABS, name: ABS}, endIndex: 30, origExpr: ABS($OLD$.quantity - quantity)}}]
    isEditable: true
  InventoryReceipt:
    _id: InventoryReceipt
    isEditable: true
    props:
      receipt_item_table: {name: receipt_item_table, propType_: CHILD_TABLE, referencedEntityName: ReceiptItem, props: {}, isLargeTable: true}
      _id: {name: _id, propType_: STRING, allowNull: false}
  ReceiptItem:
    _id: ReceiptItem
    props:
      _id: {name: _id, propType_: STRING, allowNull: false}
      product_id: {name: product_id, propType_: REFERENCE_TO, referencedEntityName: ProductLocation, referencedPropertyName: _id}
      quantity: {name: quantity, propType_: NUMBER, allowNull: false}
      price: {name: price, propType_: REFERENCE_TO, referencedEntityName: ProductLocation, referencedPropertyName: price}
      units: {name: units, propType_: CHILD_TABLE, referencedEntityName: InventoryProductUnit}
    isEditable: true
  InventoryProduct:
    _id: InventoryProduct
    props:
      code: {name: code, propType_: STRING, allowNull: false}
      barcode: {name: barcode, propType_: STRING}
      name: {name: name, propType_: STRING, allowNull: false}
      description: {name: description, propType_: STRING}
      inventory_location: {name: inventory_location, propType_: CHILD_TABLE, referencedEntityName: ProductLocation, props: {}}
      _id: {name: _id, propType_: STRING, allowNull: false}
    isEditable: true
  ProductLocation:
    _id: ProductLocation
    props:
      _id: {name: _id, propType_: STRING, allowNull: false}
      product_id: {name: product_id, propType_: STRING, allowNull: false, defaultValue: DEFAULT-location}
      location_code: {name: location_code, propType_: STRING, allowNull: false, defaultValue: DEFAULT-location}
      category: {name: category, propType_: STRING, allowNull: false}
      received_stock__: {name: received_stock__, propType_: FORMULA, formula: 'SUMIF(ReceiptItem.quantity, product_id == @[_id])'}
      available_stock__: {name: available_stock__, propType_: FORMULA, formula: received_stock__ - ordered_stock__}
      ordered_stock__: {name: ordered_stock__, propType_: FORMULA, formula: 'SUMIF(OrderItem.quantity, product_id == @[_id])'}
      price: {name: price, propType_: NUMBER, allowNull: true}
      currency: {propType_: REFERENCE_TO, referencedEntityName: General_Currency, referencedPropertyName: code, name: currency__}
      minimal_stock: {name: minimal_stock, propType_: NUMBER, allowNull: false}
      moving_stock: {name: moving_stock, propType_: NUMBER, allowNull: false}
      state: {name: state, propType_: STRING, allowNull: false}
    validations:
      positiveStock: {conditionExpr: {type: BinaryExpression, startIndex: 0, endIndex: 22, origExpr: available_stock__ >= 0, operator: '>=', left: {type: Identifier, startIndex: 0, endIndex: 17, origExpr: available_stock__, name: available_stock__}, right: {type: NumberLiteral, startIndex: 21, endIndex: 22, origExpr: '0', value: 0, raw: '0'}}}
    isEditable: true
  InventoryProductUnit:
    _id: InventoryProductUnit
    props:
      code: {name: code, propType_: STRING, allowNull: false}
      productCode: {propType_: REFERENCE_TO, name: product_code, referencedEntityName: InventoryProduct, referencedPropertyName: code}
      product_name: {propType_: REFERENCE_TO, name: product_name, referencedEntityName: InventoryProduct, referencedPropertyName: name}
      inventory_location: {name: inventory_location, propType_: STRING, allowNull: false}
      serial1: {name: serial1, propType_: STRING}
      serial2: {name: serial2, propType_: STRING}
      serial3: {name: serial3, propType_: STRING}
      serial4: {name: serial4, propType_: STRING}
      serial5: {name: serial5, propType_: STRING}
      serial6: {name: serial6, propType_: STRING}
      serial7: {name: serial7, propType_: STRING}
      install_date: {name: install_date, propType_: DATETIME}
      state: {name: state, propType_: STRING, allowNull: false}
      nb_piston_cycles: {name: nb_piston_cycles, propType_: STRING}
      brita_counter: {name: brita_counter, propType_: STRING}
      washing_cycles: {name: washing_cycles, propType_: STRING}
      _id: {name: _id, propType_: STRING, allowNull: false}
    isEditable: true
  REP:
    _id: REP
    pureNavGroupingChildren:
      - REP__DetailedCentralizerReport
      - REP__ServiceCentralizerReport
    props:
      _id: {name: _id, propType_: STRING, allowNull: false}
    isEditable: true
  LargeSalesReport:
    _id: LargeSalesReport
    props:
      client: {name: client, propType_: STRING, allowNull: false}
      month: {name: month, propType_: DATETIME}
      large_sales_product_table: {name: large_sales_product_table, propType_: CHILD_TABLE, referencedEntityName: LargeSalesProduct, isLargeTable: true, props: {}}
      _id: {name: _id, propType_: STRING, allowNull: false}
    isEditable: true
  LargeSalesProduct:
    _id: LargeSalesProduct
    props:
      product_id: {name: product_id, propType_: STRING, allowNull: false}
      product_name: {name: product_name, propType_: STRING, allowNull: false}
      large_sales_value: {name: large_sales_value, propType_: FORMULA, formula: 'SUMIF(OrderItem.quantity, product_id == @[product_id] && quantity > 100)'}
      _id: {name: _id, propType_: STRING, allowNull: false}
    isEditable: true
  GEN:
    _id: GEN
    pureNavGroupingChildren:
      - $User
      - $I18n
      - GEN__Client
      - GEN__Currency
      - GEN__Person
    props:
      _id: {name: _id, propType_: STRING, allowNull: false}
    isEditable: true
  $User:
    _id: $User
    props:
      _id: {name: _id, propType_: STRING, allowNull: false}
      role: {name: role, propType_: STRING, allowNull: false}
      password: {name: password, propType_: STRING}
      name: {name: name, propType_: STRING}
      details: {name: details, propType_: STRING}
    isEditable: true
  $I18n:
    _id: $I18n
    props:
      _id: {name: _id, propType_: STRING, allowNull: false}
      en: {name: en, propType_: STRING}
      ro: {name: ro, propType_: STRING}
    isEditable: true
