apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: formuladb
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    kubernetes.io/ingress.class: "nginx"    
    certmanager.k8s.io/issuer: "formuladb-prod"
spec:
  tls:
  - hosts:
    - formuladb.io
    secretName: certificate-formuladb-prod-root
  - hosts:
    - www.formuladb.io
    secretName: certificate-formuladb-prod-www
  rules:
  - host: formuladb.io
    http:
      paths:
      - path: /
        backend:
          serviceName: be
          servicePort: 8084
  - host: www.formuladb.io
    http:
      paths:
      - path: /
        backend:
          serviceName: be
          servicePort: 8084
