apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
spec:
  template:
    spec:
      containers:
      - name: be
        env:
        - name: FRMDB_ENV_NAME
          value: $(NAMESPACE_NAME)
        - name: FRMDB_IS_DEV_ENV
          value: "true"
        - name: FRMDB_AUTH_ENABLED
          value: "true"
        - name: FRMDB_CAN_CREATE_ENV
          value: "true"
      volumes:
      - name: git-persistence
        persistentVolumeClaim:
        hostPath:
          path: /d/code/metawiz/febe/git #TDB_PWD_ENV_DIR
          type: Directory
