apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: be
spec:
  template:
    spec:
      containers:
      - name: be
        env:
        - name: FRMDB_ENV_NAME
          value: e208-git-storage-for-tracking-history #TBD_ENV_NAME
