apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lb
spec:
  template:
    spec:
      containers:
      - name: lb
        env:
        - name: FRMDB_ENV_NAME
          value: tdev-acr #TBD_ENV_NAME
