apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: formuladb
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    kubernetes.io/ingress.class: "nginx"    
    certmanager.k8s.io/issuer: "formuladb-prod"
spec:
  tls:
  - hosts:
    - client.formuladb.io
    secretName: certificate-formuladb-prod
  rules:
  - host: client.formuladb.io
    http:
      paths:
      - path: /
        backend:
          serviceName: be
          servicePort: 8084
