_id: $App~~hotel-booking
description: 'Room Booking, Galery, Contact, Blog'
homePage: index.html
pages:
    - _footer.html
    - _form.html
    - _head.html
    - _nav.html
    - _scripts.html
    - about.html
    - booking.html
    - contact.html
    - gallery.html
    - index.html
category: 'Food & Travel, Booking & Appointments'
defaultLook: basic
defaultPrimaryColor: 008cba
defaultSecondaryColor: eeeeee
defaultTheme: Clean
