apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: formuladb
  annotations:
    # traefik.ingress.kubernetes.io/redirect-entry-point: https
    # traefik.ingress.kubernetes.io/redirect-permanent: "true"
    kubernetes.io/ingress.class: nginx
    # certmanager.k8s.io/issuer: "formuladb-staging"
spec:
  # tls:
  # - hosts:
  #   - $(NAMESPACE_NAME).formuladb.io
  #   secretName: certificate-formuladb-staging
  rules:
  - host: $(NAMESPACE_NAME).formuladb.io
    http:
      paths:
      - path: /
        backend:
          serviceName: be
          servicePort: 8084
---
apiVersion: v1
data:
  ssl-redirect: "false"
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: $(NAMESPACE_NAME)
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx