   apiVersion: certmanager.k8s.io/v1alpha1
   kind: Issuer
   metadata:
     name: formuladb-staging
   spec:
     acme:
       # The ACME server URL
       server: https://acme-staging-v02.api.letsencrypt.org/directory
       # Email address used for ACME registration
       email: laurentiu.soica@formuladb.io
       # Name of a secret used to store the ACME account private key
       privateKeySecretRef:
         name: letsencrypt-formuladb-staging
       # Enable the HTTP-01 challenge provider
       solvers:
       - http01:
           ingress:
             class: nginx
