---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: git
    spec:
      containers:
      - image: gitlab/gitlab-ce:12.0.9-ce.0
        name: be
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: git
spec:
  ports:
  - name: "api"
    port: 80
    targetPort: 80
  selector:
    service: git
status:
  loadBalancer: {}
