apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: formuladb
  annotations:
    # traefik.ingress.kubernetes.io/redirect-entry-point: https
    # traefik.ingress.kubernetes.io/redirect-permanent: "true"
    kubernetes.io/ingress.class: nginx
    # certmanager.k8s.io/cluster-issuer: "formuladb-staging"
spec:
  # tls:
  # - hosts:
  #   - $(NAMESPACE_NAME).formuladb.io
  #   secretName: certificate-formuladb-staging
  rules:
  - host: frmdb.localhost
    http:
      paths:
      - path: /formuladb
        backend:
          serviceName: be
          servicePort: 8084
      - path: /en/
        backend:
          serviceName: be
          servicePort: 8084
      - path: /ro/
        backend:
          serviceName: be
          servicePort: 8084