apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-persistence
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
