_id: FRMDB_SCHEMA~~booking
entities:
  BookingApp:
    _id: BookingApp
    pureNavGroupingChildren:
      - BookingItem
      - Booking
    props:
      _id: {name: _id, propType_: STRING, allowNull: false}
    isEditable: true
  BookingItem:
    _id: BookingItem
    isEditable: true
    props:
      name: {name: name, propType_: STRING, allowNull: false}
      description: {name: description, propType_: STRING, allowNull: false}
      picture: {name: picture, propType_: IMAGE}
      long_description: {name: long_description, propType_: STRING}
      price: {name: price, propType_: NUMBER, allowNull: false}
      wifi: {name: wifi, propType_: BOOLEAN}
      parking: {name: parking, propType_: BOOLEAN}
      _id: {name: _id, propType_: STRING, allowNull: false}
    validations:
      noOverlap: {conditionExpr: {type: BinaryExpression, startIndex: 0, endIndex: 17, origExpr: overlapping <= 10, operator: <=, left: {type: Identifier, startIndex: 0, endIndex: 11, origExpr: overlapping, name: overlapping}, right: {type: NumberLiteral, startIndex: 15, endIndex: 17, origExpr: '10', value: 10, raw: '10'}}}
  Booking:
    _id: Booking
    isEditable: true
    stateGraph:
      nodes: [PENDING, FINALIZED, CANCELLED]
      transitions: [{source: PENDING, target: FINALIZED}, {source: PENDING, target: CANCELLED}, {source: FINALIZED, target: CANCELLED}]
    props:
      user_id: {name: user_id, propType_: REFERENCE_TO, referencedEntityName: $User, referencedPropertyName: _id}
      user_name: {name: user_name, propType_: REFERENCE_TO, referencedEntityName: $User, referencedPropertyName: name}
      booking_item_id: {name: booking_item_id, propType_: REFERENCE_TO, referencedEntityName: BookingItem, referencedPropertyName: _id}
      booking_item_name: {name: booking_item_name, propType_: REFERENCE_TO, referencedEntityName: BookingItem, referencedPropertyName: name}
      booking_item_price: {name: booking_item_price, propType_: REFERENCE_TO, referencedEntityName: BookingItem, referencedPropertyName: price}
      start_date: {name: start_date, propType_: DATETIME, allowNull: false}
      end_date: {name: end_date, propType_: DATETIME, allowNull: false}
      days: {name: days, propType_: FORMULA, formula: 'DATEDIF(start_date, end_date, "D") + 1'}
      cost: {name: cost, propType_: FORMULA, formula: days * booking_item_price}
      bookings_for_the_same_room: {name: bookings_for_the_same_room, propType_: FORMULA, formula: '"FILTER(Booking, @[booking_item_id] == booking_item_id)"'}
      _id: {name: _id, propType_: STRING, allowNull: false}
  GEN:
    _id: GEN
    pureNavGroupingChildren:
      - $User
      - $I18n
      - GEN__Client
      - GEN__Currency
      - GEN__Person
    props:
      _id: {name: _id, propType_: STRING, allowNull: false}
    isEditable: true
  $User:
    _id: $User
    props:
      _id: {name: _id, propType_: STRING, allowNull: false}
      role: {name: role, propType_: STRING, allowNull: false}
      password: {name: password, propType_: STRING}
      name: {name: name, propType_: STRING}
      details: {name: details, propType_: STRING}
    isEditable: true
  $I18n:
    _id: $I18n
    props:
      _id: {name: _id, propType_: STRING, allowNull: false}
      en: {name: en, propType_: STRING}
      ro: {name: ro, propType_: STRING}
    isEditable: true
