_id: $App~~beauty-salon
defaultLook: basic
defaultPrimaryColor: 008cba
defaultSecondaryColor: eeeeee
defaultTheme: Clean
category: Booking & Appointments
description: 'Appointments, Galery, Showcase, Supplies/Beauty products, Services, Prices'
pages:
    - _footer.html
    - _form.html
    - _head.html
    - _nav.html
    - _scripts.html
    - index.html
