apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: be
spec:
  template:
    spec:
      containers:
      - name: be
        env:
        - name: FRMDB_ENV_NAME
          value: $(NAMESPACE_NAME)
        - name: FRMDB_AUTH_ENABLED
          value: "false"
        - { name: FRMDB_LOCALDEV_ENV, value: "true" }
        - { name: FRMDB_CAN_CREATE_ENV, value: "false" }
      volumes:
      - name: git-persistence
        persistentVolumeClaim:
        hostPath:
          path: /d/code/metawiz/febe/git #TDB_PWD_ENV_DIR
          type: Directory
