resources:
# - resources/be-deployment.yaml
# - resources/be-service.yaml
- resources/db-deployment.yaml
- resources/db-service.yaml
- resources/formuladb-online-https-secret.yaml
- resources/pg-persistence-persistentvolumeclaim.yaml 
# - resources/git-persistence-persistentvolumeclaim.yaml 
- resources/service-account-secret.yaml
#wildcard support removed for some reason https://github.com/kubernetes-sigs/kustomize/issues/119
