namespace: frmdb-master #TBD_ENV_NAME
resources:
- resources/be-sts.yaml
- resources/be-service.yaml
- resources/db-sts.yaml
- resources/db-service.yaml
- resources/service-account-secret.yaml
# - resources/pg-backup-deployment.yaml
#wildcard support removed for some reason https://github.com/kubernetes-sigs/kustomize/issues/119
vars:
- name: NAMESPACE_NAME
  objref:
    kind: StatefulSet
    name: be
    apiVersion: apps/v1
  fieldref:
    fieldpath: metadata.namespace
